base: core20
name: test-b00t
version: git
summary: _b00t_
description: |
  An opinionated ML Cloud/ops approach to Python, TS, & Azure
  wip. 
base: core18
confinement: devmode

parts:
  test-b00t:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-six

apps:
  test-b00t:
    command: bin/
Metadata
The snapcraft.yaml file starts with a small amount of human-readable metadata, which usually can be lifted from the GitHub description or project README.md. This data is used in the presentation of your app in the Snap Store.

name: _b00t_
version: git
summary: _b00t_
description: |_b00t_.sh
  up-cli for _b00t_

