name: RUST-CI

# This workflow run tests and build for each push
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners


on:
  push:
    branches:
      - main
      - 'feature-**'

jobs:

  build:
    # podman system service -t 0 &
    # tools/act/bin/act -P rust=ghcr.io/rust-lang/rust:nightly-buster-slim
    runs-on: ubuntu-latest
    
  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      # - name: Install jq tool
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install jq

      # - name: Update local toolchain
      #   run: |
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      #     source $HOME/.cargo/env
      #     rustup update
      #     rustup component add clippy
      #     rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      # - name: Lint
      #   run: |
      #     # cd phaser
      #     cargo fmt -- --check
      #     cargo clippy -- -D warnings          

      - name: Test
        run: |
          # cd phaser
          cargo check
          cargo test --all          

      # - name: Build
      #   run: |
      #     # cd phaser
      #     cargo build --release  


  